Table clientes {
    id int [pk, increment] // Primary Key
    correo varchar(100) [not null, unique]
    nombre varchar(100) [not null]
    apellidos varchar(100) [not null]
    password varchar(255) [not null]
    tipo_documento varchar(20) [not null]
    numero_documento varchar(20) [not null, unique]
    celular varchar(20)
}